### Tüm available hayvanları listele
GET https://petstore.swagger.io/v2/pet/findByStatus?status=available

<> 2026-03-24T105731.200.json

### Tek bir hayvan getir (id ile)
GET https://petstore.swagger.io/v2/pet/1

### Yeni hayvan ekle
POST https://petstore.swagger.io/v2/pet
Content-Type: application/json

{
  "id": 999,
  "name": "Karamel",
  "status": "available",
  "photoUrls": ["https://example.com/karamel.jpg"]
}

<> 2026-03-24T105749.200.json